version: "3.9"
services:
  nats:
    image: nats:2.10
    command: ["-js","-m","8222"]
    ports: ["4222:4222","8222:8222"]
  gateway:
    build: ./repos/at-gateway
    environment: [NATS_URL=nats://nats:4222]
    ports: ["8081:8081"]
  agent:
    build: ./repos/at-agent-mcp
    environment: [NATS_URL=nats://nats:4222]
    ports: ["8082:8082"]
  exec:
    build: ./repos/at-exec-sim
    environment: [NATS_URL=nats://nats:4222]
    ports: ["8083:8083"]
  prom:
    image: prom/prometheus
    volumes: ["./repos/at-ops/prom/prometheus.yml:/etc/prometheus/prometheus.yml"]
    ports: ["9090:9090"]
  grafana:
    image: grafana/grafana
    ports: ["3000:3000"]
