version: "3.9"

services:
  # Core messaging infrastructure
  nats:
    image: nats:2.10
    command: ["-js", "-m", "8222"]
    ports: ["4222:4222", "8222:8222"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # NATS stream initialization (runs once)
  nats-init:
    build: ./repos/at-nats-init
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222
      - STREAM_NAME=trading-events
    restart: "no"

  # Gateway service (webhooks and market data ingestion)
  gateway:
    build:
      context: ./repos
      dockerfile: at-gateway/Dockerfile
    depends_on:
      - nats-init
    environment:
      - NATS_URL=nats://nats:4222
      - API_KEY_HMAC_SECRET=test-secret
      - PORT=8001
      - LOG_LEVEL=INFO
      - REPLAY_WINDOW_SEC=3600
      # v1.0 feature flags
      - FF_TV_SLICE=true
      - FF_ENHANCED_LOGGING=false
      - FF_CIRCUIT_BREAKER=true
    ports: ["8001:8001"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  # Agent orchestrator service (GPT/Claude agents) - v1.0 NEW
  agent-orchestrator:
    build:
      context: ./repos
      dockerfile: at-agent-orchestrator/Dockerfile
    depends_on:
      - nats-init
      - redis
    environment:
      - NATS_URL=nats://nats:4222
      - REDIS_URL=redis://redis:6379
      - PORT=8010
      - LOG_LEVEL=INFO
      # v1.0 feature flags
      - FF_AGENT_GPT=true
      - FF_ENHANCED_LOGGING=false
    ports: ["8010:8010"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8010/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Output manager service (notifications & paper trading) - v1.0 NEW
  output-manager:
    build:
      context: ./repos
      dockerfile: at-output-manager/Dockerfile
    depends_on:
      - nats-init
    environment:
      - NATS_URL=nats://nats:4222
      - PORT=8008
      - LOG_LEVEL=INFO
      # v1.0 feature flags - Enable Telegram for real-world testing
      - FF_OUTPUT_SLACK=false
      - FF_OUTPUT_TELEGRAM=true
      - FF_EXEC_PAPER=true
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-}
    ports: ["8008:8008"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8008/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Redis for context storage
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Execution simulator (trade execution)
  exec:
    build: ./repos/at-exec-sim
    depends_on:
      - nats-init
    environment:
      - NATS_URL=nats://nats:4222
      - PORT=8004
      - LOG_LEVEL=INFO
    ports: ["8004:8004"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

networks:
  default:
    name: neo_minimal_default