version: "3.9"
services:
  nats:
    image: nats:2.10
    command: ["-js","-m","8222"]
    ports: ["4222:4222","8222:8222"]
  prometheus:
    image: prom/prometheus:latest
    volumes: ["./prom/prometheus.yml:/etc/prometheus/prometheus.yml"]
    ports: ["9090:9090"]
  grafana:
    image: grafana/grafana:latest
    ports: ["3000:3000"]
